env:
  name: MountainCarContinuous-v0
agent:
  explore: [1.0, 0.01, 0.0001]  # exploration probability at start, minimum exploration probability, exponential decay rate for exploration prob
  gamma: 0.99  # Also called discount factor
  memory:
    buffer_size: 10000
    batch_size: 64

actor:
  learning_rate: 0.0001
  hidden_size: [32, 64, 32]
  activation: relu

critic:
  learning_rate: 0.0001
  hidden_size_states: [32, 64]
  hidden_size_actions: [32, 64]
  activation: relu

monitor:
  num_episodes: 2000
  window: 100