env:
  name: MountainCarContinuous-v0 # MountainCarContinuous-v0 defines "solving" as getting average reward of 90.0 over 100 consecutive trials.
  seed: 23
agent:
  explore: [1.0, 0.01, 0.0001] # exploration probability at start, minimum exploration probability, exponential decay rate for exploration prob
  noise: [0, 1, 0.2]  # exploration mu, theta, sigma
  gamma: 0.99  # Also called discount factor
  tau: 0.001
  memory:
    buffer_size: 10000000
    batch_size: 128
    past_size: 20
    alpha: 1
    epsilon: 0.01

actor:
  learning_rate: 0.0001
  layers: [64, 64]

critic:
  learning_rate: 0.001
  layers: [64, 64]

monitor:
  num_episodes: 2000
  num_init_episodes: 200
  window: 100
  render: False